# UPDATED COMPREHENSIVE CONFIGURATION - All Airlines Pilot Jobs 2025
# Variables de entorno: TELEGRAM_BOT_TOKEN, TELEGRAM_CHAT_ID
# Updated URLs and selectors based on 2025 research

telegram:
  bot_token: ""        # Set via TELEGRAM_BOT_TOKEN environment variable
  chat_id: ""          # Set via TELEGRAM_CHAT_ID environment variable

# Configuración de filtrado
filtering:
  pilot_jobs_only: true
  minimum_pilot_score: 1

targets:
  # === EUROPEAN AIRLINES - PRIORITY REGION ===

  - company: "Lufthansa Group"
    region: "Europe"
    source: "html"
    url: "https://careers.lufthansagroup.com/go/Pilot-Jobs/2519010/"
    selectors:
      item: ".job-listing, .position, .career-item"
      title: ".job-title, h3, .title"
      location: ".job-location, .location"
      url: "a::attr(href)"

  - company: "British Airways"
    region: "Europe"
    source: "html"
    url: "https://careers.ba.com/pilots-jobs"
    selectors:
      item: ".job-result, .position, .job-listing"
      title: ".job-title, h3, .title"
      location: ".job-location, .location"
      url: "a::attr(href)"

  - company: "Air France"
    region: "Europe"
    source: "html"
    url: "https://www.airfranceklm.com/en/careers"
    selectors:
      item: ".job-card, .career-item, .position"
      title: ".job-title, h3, .title"
      location: ".location"
      url: "a::attr(href)"

  - company: "KLM Royal Dutch Airlines"
    region: "Europe"
    source: "html"
    url: "https://www.klm.com/careers/pilots"
    selectors:
      item: ".job-item, .career-item, .position"
      title: ".job-title, h3, .title"
      location: ".location"
      url: "a::attr(href)"

  - company: "Ryanair"
    region: "Europe"
    source: "html"
    url: "https://careers.ryanair.com/pilots/"
    selectors:
      item: ".job-card, .position, .career-item"
      title: ".job-title, h3, .title"
      location: ".location"
      url: "a::attr(href)"

  - company: "easyJet"
    region: "Europe"
    source: "html"
    url: "https://careers.easyjet.com/en/career-areas/pilots"
    selectors:
      item: ".job-item, .career-item, .position"
      title: ".job-title, h3, .title"
      location: ".location"
      url: "a::attr(href)"

  - company: "Wizz Air"
    region: "Europe"
    source: "html"
    url: "https://careers.wizzair.com/go/Pilot-Jobs/5258601/"
    selectors:
      item: ".job-listing, .position, .career-item"
      title: ".job-title, h3, .title"
      location: ".location"
      url: "a::attr(href)"

  - company: "Swiss International Air Lines"
    region: "Europe"
    source: "html"
    url: "https://www.swiss.com/ch/en/career/pilots"
    selectors:
      item: ".job-listing, .career-item"
      title: ".job-title, h3, .title"
      location: ".location"
      url: "a::attr(href)"

  - company: "Austrian Airlines"
    region: "Europe"
    source: "html"
    url: "https://www.austrian.com/career/pilots"
    selectors:
      item: ".job-offer, .position, .career-item"
      title: ".job-title, h3, .title"
      location: ".location"
      url: "a::attr(href)"

  - company: "SAS Scandinavian Airlines"
    region: "Europe"
    source: "html"
    url: "https://careers.sasgroup.net/go/All-SAS-Jobs/4164001/?utm_source=careersite&utm_campaign=sasgroup.net"
    selectors:
      item: ".job-card, .position, .career-item"
      title: ".job-title, h3, .title"
      location: ".location"
      url: "a::attr(href)"

  - company: "Finnair"
    region: "Europe"
    source: "html"
    url: "https://company.finnair.com/en/careers/pilots"
    selectors:
      item: ".job-card, .position, .career-item"
      title: ".job-title, h3, .title"
      location: ".location"
      url: "a::attr(href)"

  - company: "TAP Air Portugal"
    region: "Europe"
    source: "html"
    url: "https://www.flytap.com/en-gb/careers/pilots"
    selectors:
      item: ".job-item, .career-item, .position"
      title: ".job-title, h3, .title"
      location: ".location"
      url: "a::attr(href)"

  - company: "Norwegian Air"
    region: "Europe"
    source: "html"
    url: "https://careers.norwegian.com/pilots"
    selectors:
      item: ".job-card, .position, .career-item"
      title: ".job-title, h3, .title"
      location: ".location"
      url: "a::attr(href)"

  - company: "Turkish Airlines"
    region: "Europe"
    source: "html"
    url: "https://careers.turkishairlines.com/en-US/cockpit-crew/"
    selectors:
      item: ".job-card, .position, .career-item"
      title: ".job-title, h3, .title"
      location: ".location"
      url: "a::attr(href)"

  - company: "Pegasus Airlines"
    region: "Europe"
    source: "html"
    url: "https://www.flypgs.com/en/careers/pegasus-careers"
    selectors:
      item: ".job-card, .career-item, .position"
      title: ".job-title, h3, .title"
      location: ".location"
      url: "a::attr(href)"

  - company: "ITA Airways"
    region: "Europe"
    source: "html"
    url: "https://career.ita-airways.com/?locale=en_US"
    selectors:
      item: ".job-card, .career-item, .position"
      title: ".job-title, h3, .title"
      location: ".location"
      url: "a::attr(href)"

  # === SPANISH AIRLINES ===

  - company: "Iberia"
    region: "Europe"
    source: "html"
    url: "https://group.iberia.es/en/careers/job-vacancies/"
    selectors:
      item: ".job-card, .career-item, .position"
      title: ".job-title, h3, .title"
      location: ".location"
      url: "a::attr(href)"

  - company: "Vueling"
    region: "Europe"
    source: "html"
    url: "https://careers.vueling.com/jobs"
    selectors:
      item: ".job-card, .career-item, .position"
      title: ".job-title, h3, .title"
      location: ".location"
      url: "a::attr(href)"

  - company: "Air Europa"
    region: "Europe"
    source: "dynamic"
    url: "https://jobs.aireuropa.bizneo.cloud/jobs"
    wait_for: ".job-offer, .job-item, .job-card"
    selectors:
      item: ".job-offer, .job-item, .job-card, .career-item, .position"
      title: ".job-title, h3, .title, [data-job-title]"
      location: ".job-location, .location, .city"
      url: "a::attr(href)"

  - company: "Binter Canarias"
    region: "Europe"
    source: "dynamic"
    url: "https://trabajaconnosotros.bintercanarias.com/jobs"
    wait_for: ".job-offer, .job-item, .job-card"
    selectors:
      item: ".job-offer, .job-item, .job-card, .career-item, .position"
      title: ".job-title, h3, .title, [data-job-title]"
      location: ".job-location, .location, .city"
      url: "a::attr(href)"

  # === US MAJOR AIRLINES ===

  - company: "Delta Air Lines"
    region: "North America"
    source: "html"
    url: "https://careers.delta.com/search/?q=pilot&searchtype=1"
    selectors:
      item: ".job-listing, .position"
      title: ".job-title, h3"
      location: ".job-location, .location"
      url: "a::attr(href)"

  - company: "American Airlines"
    region: "North America"
    source: "html"
    url: "https://aa.wd1.myworkdayjobs.com/en-US/External"
    selectors:
      item: "[data-automation-id='jobTitle']"
      title: "[data-automation-id='jobTitle'] a"
      location: "[data-automation-id='locations']"
      url: "[data-automation-id='jobTitle'] a::attr(href)"

  - company: "United Airlines"
    region: "North America"
    source: "html"
    url: "https://careers.united.com/us/en/search-results?keywords=pilot"
    selectors:
      item: ".jobs-list-item, .job-card"
      title: ".job-title, h3"
      location: ".job-location, .location"
      url: "a::attr(href)"

  - company: "Southwest Airlines"
    region: "North America"
    source: "html"
    url: "https://careers.southwestair.com/job-search?keywords=pilot"
    selectors:
      item: ".job-result-item, .position"
      title: ".job-result-title, .title"
      location: ".job-result-location, .location"
      url: "a::attr(href)"

  - company: "JetBlue Airways"
    region: "North America"
    source: "html"
    url: "https://careers.jetblue.com/search/?q=pilot"
    selectors:
      item: ".job-item, .position"
      title: ".job-title, .title"
      location: ".job-location, .location"
      url: "a::attr(href)"

  - company: "Alaska Airlines"
    region: "North America"
    source: "html"
    url: "https://careers.alaskaair.com/search/?q=pilot"
    selectors:
      item: ".job-listing, .career-item"
      title: ".job-title, .title"
      location: ".location"
      url: "a::attr(href)"

  # === MIDDLE EAST AIRLINES ===

  - company: "Emirates"
    region: "Middle East"
    source: "html"
    url: "https://www.emiratesgroupcareers.com/search-and-apply/pilots/"
    selectors:
      item: ".search-result-item, .job-card"
      title: ".job-title, h3"
      location: ".job-location, .location"
      url: "a::attr(href)"

  - company: "Qatar Airways"
    region: "Middle East"
    source: "html"
    url: "https://careers.qatarairways.com/global/en/pilots"
    selectors:
      item: ".job-item, .career-item"
      title: ".job-title, h3"
      location: ".job-location, .location"
      url: "a::attr(href)"

  - company: "Etihad Airways"
    region: "Middle East"
    source: "html"
    url: "https://careers.etihad.com/go/Pilot-Jobs/716001/"
    selectors:
      item: ".job-listing, .position"
      title: ".job-title, h3"
      location: ".location"
      url: "a::attr(href)"

  # === ASIAN AIRLINES ===

  - company: "Singapore Airlines"
    region: "Asia"
    source: "html"
    url: "https://www.singaporeair.com/en_UK/es/careers/cadet-pilots-career/"
    selectors:
      item: ".job-listing, .career-item"
      title: ".job-title, .title"
      location: ".job-location, .location"
      url: "a::attr(href)"

  - company: "Cathay Pacific"
    region: "Asia"
    source: "html"
    url: "https://careers.cathaypacific.com/pilots"
    selectors:
      item: ".job-item, .position"
      title: ".job-title, .title"
      location: ".job-location, .location"
      url: "a::attr(href)"

  - company: "ANA (All Nippon Airways)"
    region: "Asia"
    source: "html"
    url: "https://www.ana.co.jp/en/jp/corporate/careers/pilot/"
    selectors:
      item: ".job-listing, .career-item"
      title: ".title, h3"
      location: ".location"
      url: "a::attr(href)"

  - company: "Japan Airlines (JAL)"
    region: "Asia"
    source: "html"
    url: "https://www.jal.com/en/career/pilot/"
    selectors:
      item: ".job-card, .position"
      title: ".title, h3"
      location: ".location"
      url: "a::attr(href)"

  # === AUSTRALIAN AIRLINES ===

  - company: "Qantas"
    region: "Oceania"
    source: "html"
    url: "https://careers.qantas.com/"
    selectors:
      item: ".job-item, .position"
      title: ".job-title, .title"
      location: ".job-location, .location"
      url: "a::attr(href)"

  - company: "Virgin Australia"
    region: "Oceania"
    source: "html"
    url: "https://www.virginaustralia.com/au/en/about-us/careers/pilot-jobs/"
    selectors:
      item: ".job-listing, .career-item"
      title: ".title, h3"
      location: ".location"
      url: "a::attr(href)"

  # === CANADIAN AIRLINES ===

  - company: "Air Canada"
    region: "North America"
    source: "html"
    url: "https://careers.aircanada.com/search/?q=pilot"
    selectors:
      item: ".job-item, .position"
      title: ".job-title, .title"
      location: ".job-location, .location"
      url: "a::attr(href)"

  - company: "WestJet"
    region: "North America"
    source: "html"
    url: "https://careers.westjet.com/search/?q=pilot"
    selectors:
      item: ".job-listing, .career-item"
      title: ".title, h3"
      location: ".location"
      url: "a::attr(href)"

  # === CARGO AIRLINES ===

  - company: "FedEx Express"
    region: "Global"
    source: "html"
    url: "https://careers.fedex.com/fedex/jobs?keywords=pilot&stretch=10&stretchUnit=MILES"
    selectors:
      item: ".job-tile, .job-item"
      title: ".job-title, h3"
      location: ".job-location, .location"
      url: "a::attr(href)"

  - company: "UPS Airlines"
    region: "Global"
    source: "html"
    url: "https://www.jobs-ups.com/search/?q=pilot"
    selectors:
      item: ".job-result-item, .search-result"
      title: ".job-result-title, .job-title"
      location: ".job-result-location, .location"
      url: "a::attr(href)"

  # === GREENHOUSE API SOURCES ===

  - company: "Uber (Aviation Division)"
    region: "Global"
    source: "greenhouse"
    slug: "uber"

  - company: "Airbnb (Travel/Aviation)"
    region: "Global"
    source: "greenhouse"
    slug: "airbnb"

  - company: "DoorDash (Aviation/Logistics)"
    region: "Global"
    source: "greenhouse"
    slug: "doordash"

  # === ENHANCED JOB BOARD SOURCES ===

  - company: "Indeed - Europe Pilots"
    region: "Europe"
    source: "indeed"
    query: "airline pilot"
    location: "Europe"
    limit: 30

  - company: "Indeed - US Pilots"
    region: "North America"
    source: "indeed"
    query: "commercial pilot airline"
    location: "United States"
    limit: 30

  - company: "Indeed - Global Pilots"
    region: "Global"
    source: "indeed"
    query: "pilot captain first officer"
    location: ""
    limit: 50

  - company: "Aviation Job Boards"
    region: "Global"
    source: "aviation_jobs"
    source_type: "all"