name: Pilot Job Tracker

on:
  schedule:
    # Run every 15 minutes
    - cron: '*/15 * * * *'

  # Allow manual triggering
  workflow_dispatch:
    inputs:
      config_file:
        description: 'Config file to use'
        required: false
        default: 'config_enhanced.yml'
        type: string

jobs:
  track_jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: Run job tracker
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          CONFIG_PATH: ${{ inputs.config_file || 'config_enhanced.yml' }}
        run: python main.py

      - name: Upload database as artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: jobs-database-${{ github.run_number }}
          path: jobs.db
          retention-days: 30

      - name: Upload logs as artifact
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: logs-${{ github.run_number }}
          path: |
            *.log
            error.log
          retention-days: 7
