name: Jobs Watcher

on:
  schedule:
    - cron: "*/30 * * * *"   # cada 30 min
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Si usas Playwright:
          python -m playwright install --with-deps chromium
      - name: Run watcher
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          cp config.example.yml config.yml  # o sube el tuyo encriptado con secrets
          python main.py
      - name: Persist DB
        uses: actions/upload-artifact@v4
        with:
          name: jobs-db
          path: jobs.db
